services:
  dev:
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
    network_mode: host
    volumes:
      - ..:/root/workspace:delegated
      - ./.bashrc:/root/.bashrc
      - ./.bash_aliases:/root/.bash_aliases
      - ./.bash_functions:/root/.bash_functions

    command: sleep infinity # Keep container running for VS Code to connect